[ env ]
TERM = "xterm-256color"

[window]

padding.x = 10
padding.y = 10
dynamic_padding = true

startup_mode = "Fullscreen"

# decorations = "Full"
decorations = "Buttonless"
decorations_theme_variant = "Dark" 

dynamic_title = false

option_as_alt = "Both"

[font]

normal.family = "ComicShannsMono Nerd Font"

size = 19.0

[colors]

cursor.cursor = "#ffffff"
vi_mode_cursor.cursor = "#ffffff"

[cursor]

style.shape = "Block"
style.blinking = "Off"

[mouse]

hide_when_typing = true
