[window]

opacity = 1

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" 

[font]

normal.family = "CaskaydiaMono Nerd Font Mono"
bold.family = "CaskaydiaMono Nerd Font Mono"
italic.family = "CaskaydiaMono Nerd Font Mono"
bold_italic.family = "CaskaydiaMono Nerd Font Mono"

size = 18.0

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.
