[ env ]
TERM = "xterm-256color"

[window]

opacity = 1

padding.x = 4
padding.y = 4
dynamic_padding = true

startup_mode = "Fullscreen"

# decorations = "Full"
decorations = "Buttonless"
decorations_theme_variant = "Dark" 

dynamic_title = false

option_as_alt = "OnlyLeft"

[font]

normal.family = "CaskaydiaMono Nerd Font Mono"
bold.family = "CaskaydiaMono Nerd Font Mono"
italic.family = "CaskaydiaMono Nerd Font Mono"
bold_italic.family = "CaskaydiaMono Nerd Font Mono"

size = 19.0

[colors]

primary.background = "#1a1b26"

cursor.cursor = "#ffffff"
vi_mode_cursor.cursor = "#ffffff"

[cursor]

style.shape = "Block"
style.blinking = "Off"

[mouse]

hide_when_typing = true
